[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist' by default)
  publish = "dist"

# Production environment variables for Netlify
[build.environment]
  VITE_API_URL = "https://bootcampsimulator.sadlers.cloud"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: Preview builds (for deploy previews)
[context.deploy-preview]
  environment = { VITE_API_URL = "https://bootcampsimulator.sadlers.cloud" }

# Optional: Branch deploys
[context.branch-deploy]
  environment = { VITE_API_URL = "https://bootcampsimulator.sadlers.cloud" }
