name: Backend Tests

on:
  push:
    branches: [main, testing]
    paths:
      - "backend/**"
      - ".github/workflows/backend-tests.yml"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_flask.txt

      - name: Run tests with pytest
        working-directory: ./backend
        run: |
          python -m pytest tests/ --cov=. --cov-report=term-missing -v
